[project]
name = "quantumct-rtrc-qbraid-challenge"
version = "0.1.0"
description = "QuantumFrenchVanilla submission for the YQuantum QuantumCT X RTRC X qbraid challenge"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.4",
    "qiskit>=2.3.1",
    "scipy>=1.17.1",
]
